server:
  port: 8081
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/likelion-db
    username: qwer
    password: qwer

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  token:
    secret: hihi